name: Deploy re4u bot
on:
  push:
    branches:
      - master

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  BASE_URL: ${{ secrets.BASE_URL }}
  NSEC_KEY: ${{ secrets.NSEC_KEY }}

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.10.10

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: python -m unittest tests/test_utils.py

      - name: Generate coverage report
        run: |
          pip install coverage
          coverage run -m unittest tests/test_utils.py
          coverage report
          coverage xml

      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
